name: "Deploy to vercal"

on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - uses: pnpm/action-setup@v4
              with:
                  version: 10
            - run: pnpm install
            - run: pnpm lint

    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: nexterias/actions-vercel@v1
              with:
                  token: ${{ secrets.VERCEL_TOKEN }}
                  project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  production: ${{ github.ref == 'refs/heads/main' }}
                  prebuilt: false # If set to true, build will be performed using GitHub Actions.

